[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Dependencies for the PCA9685 PWM Driver
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1
    Wire
